### ISSUE TITLE
[Code UW]: Offshore Geodesy - Add API Reference page for modules

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/codeuw#22]
### Contact

landungs@uw.edu

### Description

The offshore geodesy project with the package creation of `gnatss` currently has a documentation hosted in Read the docs as seen [here](https://gnatss.readthedocs.io/en/latest/intro.html). [Read the Docs](https://readthedocs.org/) builds, version, and host the documentation. Currently the documentation is developed with [Jupyterbook](https://jupyterbook.org/en/stable/intro.html), a software for developing documents. Jupyterbook is built on top of [Sphinx](https://www.sphinx-doc.org/en/master/index.html), which is a Python document generator.

The task is to do the following:
- [x] Add the [`autodoc`](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) extension to the jupyterbook configuration
- [x] Add the [`napoleon`](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#module-sphinx.ext.napoleon) extension to expose the docstrings within the code for the modules created for `gnatss` so far.
- [x] Add an API Reference page to expose the functions and modules in [`utilities`](https://github.com/uw-ssec/offshore-geodesy/tree/main/src/gnatss/utilities) and [`ops`](https://github.com/uw-ssec/offshore-geodesy/tree/main/src/gnatss/ops)

### Code Repository

https://github.com/uw-ssec/offshore-geodesy

### Issue link

https://github.com/uw-ssec/offshore-geodesy/issues/54

### Task level

L2

### What is the primary programming language for the task

python

**Comment by lsetiawan** [comment]
Done
